In [1]:
import numpy as np
from scipy import linalg

## Inverse of matrix

In [2]:
matrix = np.array([[10,6],[2,7]])
matrix

array([[10,  6],
       [ 2,  7]])

In [3]:
type(matrix)

numpy.ndarray

In [4]:
linalg.inv(matrix)

array([[ 0.12068966, -0.10344828],
       [-0.03448276,  0.17241379]])

## Finfing Determinant

In [5]:
matrix = np.array([[10,6],[2,7]])
matrix

array([[10,  6],
       [ 2,  7]])

In [6]:
linalg.det(matrix)

58.0

## Solve Linear systems

In [8]:
numArray = np.array([[2,3,1],[-1,5,4],[3,2,9]])

In [11]:
numArrValue = np.array([21,9,6])

In [12]:
linalg.solve(numArray, numArrValue)

array([ 4.95,  4.35, -1.95])

## Single Value Decomposition(SVD)

In [13]:
numSvdArr = np.array([[3,5,1],[9,5,7]])

In [14]:
numSvdArr.shape

(2, 3)

In [15]:
linalg.svd(numSvdArr)

(array([[-0.37879831,  0.92547925],
        [-0.92547925, -0.37879831]]),
 array([13.38464336,  3.29413449]),
 array([[-0.7072066 , -0.4872291 , -0.51231496],
        [-0.19208294,  0.82977932, -0.52399467],
        [-0.68041382,  0.27216553,  0.68041382]]))