# Quick Recap: Lists

In [3]:
# Below are some of the properties of lists:

distance = [10, 15, 17, 26] # Colletion of values
time = [.30, .47, .55, 1.20] # Multiple types (Heterogeneous)
print(distance)
print(time) 

[10, 15, 17, 26]
[0.3, 0.47, 0.55, 1.2]


# Limitations of Lists

In [ ]:
# You can change individual values in a list, but you cannot apply a mathematical operation over the entire list.

speed = distance / time # Mathematical operation over the entire “distance” and “time” lists

# Error: unsuppoerted operation types

# Why NumPy

In [5]:
# Numerical Python (NumPy) supports multidimensional arrays
# over which you can easily apply mathematical operations.


distance = [10, 15, 17, 26] # Colletion of values
time = [.30, .47, .55, 1.20] # Multiple types (Heterogeneous)

In [7]:
import numpy as np

In [8]:
np_distance = np.array(distance) #Create 'distance' and 'time' NumPy arrays
np_time = np.array(time) 

speed = np_distance / np_time # Mathematical function applied over the entire 'distance' and 'time' arrays

In [9]:
speed

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

# Types of Arrays

In [11]:
# Arrays can be one-dimensional, two-dimensional, three-dimensional, or multi-dimensional.

In [13]:
# One-dimensional array

array = [5, 7, 9]
one = np.array(array)
one # Printed as rows

array([5, 7, 9])

In [15]:
# Two-dimensional array

array = [[0, 1, 2],[5, 6, 7]]
two = np.array(array)
two # Printed as matrices (2x3)

array([[0, 1, 2],
       [5, 6, 7]])

In [16]:
# Three-dimensional array

array = [[[0,1,2],[3,4,5],[6,7,8]], [[9,10,11],[12,13,14],[15,16,17]],[[18,19,20],[21,22,23],[24,25,26]]]

three = np.array(array)
three #Printed as list od matrices (3x3x3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])