# Basic Operations

In [1]:
import numpy as np

In [2]:
a_trial_cyclist = [10, 15, 17, 26]

In [3]:
b_trial_cyclist = [12, 11, 21, 24]

In [4]:
np_a_trial = np.array(a_trial_cyclist)

In [5]:
np_b_trail = np.array(b_trial_cyclist)

In [6]:
np_a_trial + np_b_trail # Total distance

array([22, 26, 38, 50])

# Accessing Array Elements: Indexing

In [7]:
# You can access an entire row of an array by referencing its axis index.

cyclist_trial = np.array([[10, 15, 17, 26],[12, 11, 21, 24]])

In [16]:
one_trial = cyclist_trial[0] # First trial data

In [9]:
one_trial

array([10, 15, 17, 26])

In [10]:
two_trial = cyclist_trial[1] #Second trial data

In [11]:
two_trial

array([12, 11, 21, 24])

In [12]:
# You can refer the indices of the elements in an array to access them. 
# You can also select a particular index of more than one axis at a time.

one_cyclist_one_trial = cyclist_trial[0][0] #First cyclist: first trial data

In [13]:
one_cyclist_one_trial

10

In [14]:
one_cyclist_all_trial = cyclist_trial[:,0] # First cyclist: all trial data

In [15]:
one_cyclist_all_trial

array([10, 12])

# Accessing Array Elements: Slicing

In [17]:
# Use the slicing method to access a range of values within an array.

cyclist_trial.shape

(2, 4)

In [18]:
two_cyclist_trial_data = cyclist_trial[:, 1:3] #Slincing the array data, where 1 is inclusive but 3 is not

In [19]:
two_cyclist_trial_data

array([[15, 17],
       [11, 21]])

# Accessing Array Elements: Iteration

In [21]:
# Use the iteration method to go through each data element present in the dataset.

# Iterate with for loop through entire dataset
for iterate_cyclist_trial_data in cyclist_trial:
    print(iterate_cyclist_trial_data)

[10 15 17 26]
[12 11 21 24]


In [22]:
# Iterate with for loop through the two cyclist datasets
for iterate_two_cyclist_trial_data in two_cyclist_trial_data:
    print(iterate_two_cyclist_trial_data)

[15 17]
[11 21]


# Indexing with Boolean Arrays

In [23]:
# Here, the original dataset contains test scores of two students.
# You can use a Boolean array to choose only the scores that are above a given value.


test_scores = np.array([[83,71,57,63],[54,68,81,45]])

In [24]:
passing_score = test_scores > 60 

In [26]:
passing_score

array([[ True,  True, False,  True],
       [False,  True,  True, False]])

In [28]:
test_scores[passing_score] # Send passing score as an argument to test scores object

array([83, 71, 63, 68, 81])

# Copy and Views

## Simple Assingnments

In [29]:
# In this method, a variable is directly assigned the value of another variable. No new copy is made.

NYC_Borough = np.array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'])

In [30]:
NYC_Borough 

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [31]:
Borough_in_NYC = NYC_Borough

In [32]:
Borough_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [33]:
Borough_in_NYC is NYC_Borough 

True

## View / Shallow Copy

In [34]:
# A view, also referred to as a shallow copy, creates a new array object.

View_of_Borough_in_NYC = Borough_in_NYC.view()

In [35]:
len(View_of_Borough_in_NYC)

5

In [36]:
View_of_Borough_in_NYC[4] = 'Central Park' # Change value in view object

In [37]:
View_of_Borough_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Central Park'],
      dtype='<U13')

In [38]:
Borough_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Central Park'],
      dtype='<U13')

## Deep Copy

In [39]:
# Copy is also called deep copy because it entirely copies the original dataset. 
# Any change in the copy will not affect the original dataset.

Copy_of_NYC_Borough = NYC_Borough.copy()

In [40]:
Copy_of_NYC_Borough is NYC_Borough

False

In [41]:
Copy_of_NYC_Borough.base is NYC_Borough

False

In [42]:
Copy_of_NYC_Borough[4] = 'Central Park' # Change value in copy

In [43]:
NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Central Park'],
      dtype='<U13')

In [44]:
Copy_of_NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Central Park'],
      dtype='<U13')

# Universal Functions (ufunc)

 **sqrt** unction provides the square root of every element in the array.

In [45]:
np_sqrt = np.sqrt([2,4,9,16])

In [46]:
np_sqrt

array([1.41421356, 2.        , 3.        , 4.        ])

**floor** function returns the largest integer value of every element in the array.

In [50]:
np.floor([1.5,1.6,2.7,3.3,1.1,-0.3,-1.4])

array([ 1.,  1.,  2.,  3.,  1., -1., -2.])

**cos** function gives cosine values for all elements in the array.

In [47]:
from numpy import pi
np.cos(0)

1.0

In [48]:
np.sin(pi/2)

1.0

In [49]:
np.cos(pi)

-1.0

**exp** function performs exponentiation on each element.

In [51]:
np.exp([0,1,5])

array([  1.        ,   2.71828183, 148.4131591 ])

# Shape Manipulation

In [53]:
# The shape of an array can be changed according to the requirement using the NumPy library functions.
cy_trial = np.array([[10, 15, 17, 26,13,19],[12, 11, 21, 24,14,23]])

In [54]:
cy_trial.ravel() # Flattens the dataset

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [55]:
cy_trial.reshape(3,4) # Changes or reshapes the dataset to 3 rows and 4 columns

array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 23]])

In [56]:
cy_trial.resize(2,6) # Resizes again to 2 rows and 6 columns

In [57]:
cy_trial

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [58]:
np.hsplit(cy_trial,2) #Splits the array into two

[array([[10, 15, 17],
        [12, 11, 21]]),
 array([[26, 13, 19],
        [24, 14, 23]])]

In [60]:
cy_trial_1 = np.array([10, 15, 17, 26,13,19])

In [61]:
cy_trial_2 = np.array([12, 11, 21, 24,14,23])

In [62]:
np.hstack((cy_trial_1,cy_trial_2)) # Stacks the arrays together

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

# Broadcasting

In [63]:
# NumPy uses broadcasting to carry out arithmetic operations between arrays of different shapes. 
# In this method, NumPy automatically broadcasts the smaller array over the larger array.

import numpy as np

In [64]:
# Create two arrays of the same shape
array_a = np.array([2,3,5,8])
array_b = np.array([.3,.3,.3,.3])

In [65]:
#Multiply arrays
array_a * array_b

array([0.6, 0.9, 1.5, 2.4])

In [66]:
# Create a variable with a scalar value
scalar_c = .3

In [67]:
# Multiple 1D array with a scalar value
array_a * scalar_c

array([0.6, 0.9, 1.5, 2.4])

# Linear Algebra: Transpose

In [68]:
# NumPy can carry out linear algebraic functions as well. 
# The transpose() function can help you interchange rows as columns, and vice-versa.

test_scores = np.array([[83,71,57,63],[54,68,81,45]])

In [69]:
test_scores.transpose()

array([[83, 54],
       [71, 68],
       [57, 81],
       [63, 45]])

# Linear Algebra: Inverse and Trace Functions

In [70]:
# Using NumPy, you can also find the inverse of an array and add its diagonal data elements.

inverse_array = np.array([[10,20],[15,25]])

In [71]:
# np.linalg.inv() - Inverse of the given array
np.linalg.inv(inverse_array)

array([[-0.5,  0.4],
       [ 0.3, -0.2]])

In [72]:
# np.trace() - Sum of diagonal elements 10 and 31
trace_array = np.array([[10,20],[22,31]])

In [73]:
np.trace(trace_array)

41